#!/bin/bash
# Apache License 2.0

# Install Jupyter widgets extension

# Install Open Space Toolkit default datasets

################################################################################################################################################################
