#!/bin/bash
# Apache License 2.0

# Install Jupyter widgets extension

# Install Open Space Toolkit default datasets

mkdir -p /home/jovyan/open-space-toolkit/physics
gsutil -m cp -r gs://open-space-toolkit/physics /home/jovyan/open-space-toolkit/

################################################################################################################################################################
