# Apache License 2.0

name: Benchmark and Validate

on:
  workflow_call:
    inputs:
      project_name:
        description: The name of the project.
        required: true
        type: string
      project_version:
        description: The version of the project.
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  DOCKER_REGISTRY_PATH: openspacecollective
  LANG: en_US.UTF-8

jobs:
  benchmark-cpp:
    name: Benchmark C++
    runs-on: ubuntu-24.04
    container:
      image: openspacecollective/${{ inputs.project_name }}-development:${{ inputs.project_version }}
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Build
        run: cd /app && make _build-test
      - name: Run C++ Benchmark
        run: /app/bin/${{ inputs.project_name }}.benchmark --benchmark_out_format=json --benchmark_out=/app/bin/benchmark_result.json
      - name: Upload benchmark result
        uses: actions/upload-artifact@v6
        with:
          name: benchmark-result
          path: /app/bin/benchmark_result.json

  benchmark-cpp-report:
    name: Report C++ Benchmark
    needs: benchmark-cpp
    runs-on: ubuntu-24.04
    steps:
      - name: Download benchmark result
        uses: actions/download-artifact@v8
        with:
          name: benchmark-result
      - name: Download previous benchmark
        uses: actions/cache@v5
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "googlecpp"
          output-file-path: benchmark_result.json
          external-data-json-path: ./cache/benchmark-data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.ref == 'refs/heads/main' }}
          alert-threshold: "200%"
          comment-on-alert: true

  validation-cpp:
    name: Run C++ Validation Tests
    runs-on: ubuntu-24.04
    container:
      image: openspacecollective/${{ inputs.project_name }}-development:${{ inputs.project_version }}
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Build
        run: cd /app && make _build-test
      - name: Run C++ Validation Tests
        run: /app/bin/${{ inputs.project_name }}.validation
