# Apache License 2.0

name: Build Packages

on:
  workflow_call:
    inputs:
      project_name:
        description: The name of the project.
        required: true
        type: string
      project_version:
        description: The version of the project.
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  DOCKER_REGISTRY_PATH: openspacecollective
  LANG: en_US.UTF-8

jobs:
  build-packages:
    name: Build all packages
    strategy:
      fail-fast: true
      matrix:
        architecture:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.architecture.runner }}
    container:
      image: openspacecollective/${{ inputs.project_name }}-development:${{ inputs.project_version }}
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Build Packages
        # if: matrix.architecture.platform != 'linux/arm64' || github.ref == 'refs/heads/main' || (github.event_name == 'release' && github.event.action == 'published')
        run: cd /app && make _build-release-packages
        env:
          CESIUM_TOKEN: ${{ secrets.CESIUM_TOKEN }}
      - name: Format artifact name
        id: format-artifact-name
        # if: matrix.architecture.platform != 'linux/arm64' || github.ref == 'refs/heads/main' || (github.event_name == 'release' && github.event.action == 'published')
        run: |
          artifact_name=$(echo "${{ matrix.architecture.platform }}" | tr / -)
          echo "ARTIFACT_NAME=${artifact_name}" >> $GITHUB_OUTPUT
      - name: Upload C++ Package
        # if: matrix.architecture.platform != 'linux/arm64' || github.ref == 'refs/heads/main' || (github.event_name == 'release' && github.event.action == 'published')
        env:
          ARTIFACT_NAME: ${{ steps.format-artifact-name.outputs.ARTIFACT_NAME }}
        uses: actions/upload-artifact@v6
        with:
          name: cpp-package-${{ env.ARTIFACT_NAME }}
          path: /app/packages/cpp/
      - name: Upload Python Package
        # if: matrix.architecture.platform != 'linux/arm64' || github.ref == 'refs/heads/main' || (github.event_name == 'release' && github.event.action == 'published')
        env:
          ARTIFACT_NAME: ${{ steps.format-artifact-name.outputs.ARTIFACT_NAME }}
        uses: actions/upload-artifact@v6
        with:
          name: python-package-${{ env.ARTIFACT_NAME }}
          path: /app/packages/python/
      - name: Tar files
        if: matrix.architecture.platform == 'linux/amd64'
        run: cd /app && tar -cvf docs.tar.gz docs/
      - name: Upload Documentation
        if: matrix.architecture.platform == 'linux/amd64'
        uses: actions/upload-artifact@v6
        with:
          name: docs
          path: /app/docs.tar.gz
