# Apache License 2.0

name: Test

on:
  workflow_call:
    inputs:
      project_name:
        description: The name of the project.
        required: true
        type: string
      project_version:
        description: The version of the project.
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  DOCKER_REGISTRY_PATH: openspacecollective
  LANG: en_US.UTF-8

jobs:
  format-check-cpp:
    name: Check C++ Format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull Development Image
        run: docker pull ${{ env.DOCKER_REGISTRY_PATH }}/${{ inputs.project_name }}-development:${{ inputs.project_version }}
      - name: Check C++ Format
        run: make format-check-cpp-standalone

  format-check-python:
    name: Check Python Format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull Development Image
        run: docker pull ${{ env.DOCKER_REGISTRY_PATH }}/${{ inputs.project_name }}-development:${{ inputs.project_version }}
      - name: Check Python Format
        run: make format-check-python-standalone

  build-tests-and-coverage:
    name: Build all tests and run coverage
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull Development Image
        run: docker pull ${{ env.DOCKER_REGISTRY_PATH }}/${{ inputs.project_name }}-development:${{ inputs.project_version }}
      - name: Run Coverage
        run: make build-tests
      - name: Upload Coverage Results
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true
      - name: Upload Python Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-bindings # TBM: use a different namespace than in build-packages for now.
          path: build/bindings/python
      - id: python-versions
        name: Export Python Versions to Environment
        run: |
          python_versions=$(echo -n "["; ls -d build/bindings/python/OpenSpaceToolkit*-python-package-*/ | grep -o -E '[0-9]+\.[0-9]+' | sed "s/\(.*\)/'\1'/" | tr '\n' ',' | sed 's/,$//'; echo "]")
          echo "Python versions: ${python_versions}"
          echo "value=${python_versions}" >> $GITHUB_OUTPUT

  test-unit-python:
    name: Run Python Unit Tests
    runs-on: ubuntu-24.04
    needs:
      - build-tests-and-coverage
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.build-tests-and-coverage.outputs.python_versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull Development Image
        run: docker pull ${{ env.DOCKER_REGISTRY_PATH }}/${{ inputs.project_name }}-development:${{ inputs.project_version }}
      - name: Download Python packages
        uses: actions/download-artifact@v4
        with:
          name: python-bindings
          path: build/bindings/python
      - name: Run Unit Tests Python
        run: make ci-test-python ${{ format('test_python_version={0}', matrix.python-version) }}
