# Apache License 2.0

name: Test

on:
  workflow_call:
    inputs:
      project_name:
        description: The name of the project.
        required: true
        type: string
      project_version:
        description: The version of the project.
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  DOCKER_REGISTRY_PATH: openspacecollective
  LANG: en_US.UTF-8

jobs:
  format-check-cpp:
    name: Check C++ Format
    runs-on: ubuntu-24.04
    container:
      image: openspacecollective/${{ inputs.project_name }}-development:${{ inputs.project_version }}
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Check C++ Format
        run: ostk-check-format-cpp

  format-check-python:
    name: Check Python Format
    runs-on: ubuntu-24.04
    container:
      image: openspacecollective/${{ inputs.project_name }}-development:${{ inputs.project_version }}
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Check Python Format
        run: ostk-check-format-python

  build-artifacts:
    name: Build Artifacts
    runs-on: ubuntu-24.04
    container:
      image: openspacecollective/${{ inputs.project_name }}-development:${{ inputs.project_version }}
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    outputs:
      python_versions: ${{ steps.python-versions.outputs.value }}
    steps:
      - name: Build artifacts
        run: cd /app && make _build-test
      - name: Export Python Versions
        id: python-versions
        run: |
          python_versions=$(ls /app/build/bindings/python/ \
            | grep -oE '[0-9]+\.[0-9]+$' \
            | sort -Vu \
            | sed 's/.*/"\0"/' \
            | paste -sd ',' \
            | sed 's/^/[/' | sed 's/$/]/')
          echo "Python versions: ${python_versions}"
          echo "value=${python_versions}" >> $GITHUB_OUTPUT
      - name: Copy artifacts to workspace
        run: |
          cp -a /app/build $GITHUB_WORKSPACE/build
          cp -a /app/bin $GITHUB_WORKSPACE/bin
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ inputs.project_version }}
          path: ${{ github.workspace }}/
          retention-days: 1

  test-unit-cpp:
    name: Run C++ Unit Tests
    runs-on: ubuntu-24.04
    container:
      image: openspacecollective/${{ inputs.project_name }}-development:${{ inputs.project_version }}
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    needs:
      - build-artifacts
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ inputs.project_version }}
          path: ${{ github.workspace }}/artifacts
      - name: Restore build artifacts
        run: |
          cp -a $GITHUB_WORKSPACE/artifacts/build/. /app/build/
          mkdir -p /app/bin
          cp -a $GITHUB_WORKSPACE/artifacts/bin/. /app/bin/
      - name: Run Unit Tests C++
        run: |
          cd /app/build
          make coverage
      - name: Upload Coverage Results
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /app/build/coverage.info
          fail_ci_if_error: true

  test-unit-python:
    name: Run Python Unit Tests
    runs-on: ubuntu-24.04
    container:
      image: openspacecollective/${{ inputs.project_name }}-development:${{ inputs.project_version }}
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    needs:
      - build-artifacts
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.build-artifacts.outputs.python_versions) }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ inputs.project_version }}
          path: ${{ github.workspace }}/artifacts
      - name: Restore build artifacts
        run: |
          cp -a $GITHUB_WORKSPACE/artifacts/build/. /app/build/
          mkdir -p /app/bin
          cp -a $GITHUB_WORKSPACE/artifacts/bin/. /app/bin/
      - name: Run Unit Tests Python
        run: ${{ format('OSTK_PYTHON_VERSION={0}', matrix.python-version) }} ostk-test-python
